### ISSUE TITLE
你是否能完成游戏

### ISSUE THREAD

**Issue by Lin07ux** [luozhihao/vue-puzzle#1]
你好，我想问下，加了边界条件限制（在左边界不能移动到上一行的右边界，在右边界不能移动到下一行左边界）的情况下，你是否完成了游戏呢？如果完成了，能否告诉我在下面的情况下，如何将 12  移动到左下角吗？

<img src="http://7xkt52.com1.z0.glb.clouddn.com/markdown/1471103807274.png" width="441"/>

**Comment by luozhihao** [comment]
之前没有加边界条件限 就会存在在左边界可以移动到上一行的右边界，在右边界可以移动到下一行左边界的情况，这是一个bug，是不符合拼图逻辑的。加了之后你说的情况我试了下是可以实现，毕竟所有数字拼图的逻辑都是这样的，为什么不能完成呢？

**Comment by Lin07ux** [comment]
确实是我自己考虑的少了，是可以完成的。

另外，关于是否是处于左边界的情况下，可以考虑使用`!(index  %  4)`判断，是否在右边界可以考虑使用`3 === index % 4`来判断，更简洁一些。

**Comment by luozhihao** [comment]
嗯，可以的，不过条件写反了，index % 4 和 3 !== index % 4

**Comment by zhu-Newbie** [comment]
![qq 20160925143542](https://cloud.githubusercontent.com/assets/22424651/18813479/f1d4fa50-832d-11e6-982e-86a7547ae15d.png)
